#travis configuration for coverage testing
language: c

matrix:
  include:
    - os: linux
      compiler: gcc
      before_install:
        - sudo apt-get install automake autoconf libtool check lcov
    - os: osx
      compiler: gcc
      before_install:
        - brew install autoconf libtool check lcov
    - os: osx
      compiler: clang
      before_install:
        - brew install autoconf libtool check lcov

before_script:
- cd ${TRAVIS_BUILD_DIR}
- lcov --directory . --zerocounters

# Build steps
script:
  - cd ${TRAVIS_BUILD_DIR}
  - sh ./build.sh init
  - ./configure
  - make
  - make check

after_success:
- cd ${TRAVIS_BUILD_DIR}
- lcov --directory . --capture --output-file coverage.info # capture coverage info
- lcov --remove coverage.info 'test/*' '/usr/*' --output-file coverage.info # filter out system and test code
- lcov --list coverage.info # debug before upload
- coveralls-lcov  coverage.info #for open source
